### PR TITLE
Use Token Auth

### PR DESCRIPTION
**Pull request by tmuntaner**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-build-image-sle12sp3. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-build-image-sle12sp3. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step rspec. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged c3192949f24e52138d735d5d1af6a56932df7350 into dddaf68d44966168ade7eea27c3e2c4da0d5d982)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
